name: Cleanup old branches
on:
  schedule:
    - cron:  '0 1 * * *'
jobs:
  housekeeping:
    name: Cleanup old branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Delete old branches
        uses: beatlabs/delete-old-branches-action@v0.10.0
        with:
          repo_token: ${{ github.token }}
          date: '2 weeks ago'
          default_branches: main,master,scratch
          extra_protected_branch_regex: ^(release-*|master_*)$
          exclude_open_pr_branches: true
          dry_run: false
          delete_tags: true
